### ISSUE TITLE
Instead of requiring a full @Id URI, only request a Ctid

### ISSUE THREAD

**Issue by cwd-mparsons** [CredentialEngine/Registry_Assistant#1]
@stuartasutton  @jkitchensSIUC @siuc-nate 
When referencing an organization, an @Id is typically used to reference an organization in the registry. The API uses the OrganizationReference class (inherits from an Entityreference), to allow providoing an @Id, OR, an Ctid, OR a third party organization:
https://github.com/CredentialEngine/Registry_Assistant/blob/master/src/RA.Models/Input/profiles/OrganizationReference.cs

I suggest that for the RA API, we only expose the Ctid property. This approach means a user doesn't have to know the actual Url for a registry resource. The RA API will provide the proper url for the current environment (sandbox, staging, production).

The latter class can also be used to enter a reference to a third party organization that does not exist in the registry, or a user may not know exists in the registry.

**Comment by stuartasutton** [comment]
I find it odd that for something as opaque as a UUID, that a CTID for a person would be readily available and a URI based on the CTID would not. Other than that, I really need to leave the Registry Assistant matter to you folks implementing. Do we have a bulleted list of exactly what the Registry Assistant API enables?

**Comment by cwd-mparsons** [comment]
This issue was for flexibility, and not implemented. 
With the recent change for entity references to be a list of strings, rather than objects, the 'feature' would not have been straight-forward - closing.

**Comment by stuartasutton** [comment]
@cwd-mparsons, @jkitchensSIUC, @siuc-nate, I reopened this issue because I want to make sure I understand. Are you saying that a `CredentialOrganization` identifies it's credentials with something like `"owns": "http://......."` as opposed to `"owns: {"@id": "http://......."}`? I don't know how I would have missed that. If so, it basically means that we've added a means for an org to **signal** what it owns; but we know that the data is useless as linked data in the wild. 

I recall the original rationale was (under my objection) not to add any reference from an organization record to that it owns because it would mean updating/resigning the org record every time a new credential was added. Seems now that it is OK to add a mention (but not a linkable reference). What is the rationale now?

**Comment by siuc-nate** [comment]
@stuartasutton There are two related things at play here:

First, the change to the structure was part of the updates to the context file a long while back.  `ceterms:owns` (and `ceterms:offers`, and a number of other properties that point to URIs or instances of CTDL classes) is defined as `{ "@type": "@id" }` in the [context](http://credreg.net/ctdl/schema/context/json), so there is no need to use an object with an `@id` property anymore. `"ceterms:owns": [ "http://..." ]` would still be linked data with that context.

The second part is providing the information in the organization record.  This is something that @jkitchensSIUC has recently raised while discussing the minimum data policy (specifically, to make owns and offers **required** fields on `ceterms:CredentialOrganization` records and **required if available** fields on `ceterms:QACredentialOrganization` records).  I can see some utility in this, but I also share your concerns, as this means:
- **A.** The organization record needs to be updated every time something new is offered (or ceases being offered), and every time something new is created
- **B.** There is the potential for inconsistent data (e.g. newly-published credential says it's offered by organization A, but organization A's record hasn't been updated to reflect this in its "owns" property. A system consumes both records. What conclusion does it draw?)
  - **B1.** This is potentially magnified in cases where an organization offers credentials owned by another organization (e.g. A newly-published credential says it's owned by Organization A and offered by Organization B; but Organization A can't force an update to Organization B's record to reflect the inverse. A system consumes all three records. What conclusion does it draw?)
  - **B2.** The same applies in reverse (e.g. Organization A's record says that it offers a credential it does not own, and therefore cannot force an update to the credential record to say that it is offered by that organization)
- **C.** It is redundant anyway **if** the relationship is reliably provided in the credential record, since that this can be determined by querying inverse properties (e.g. find out everything an organization owns or offers by querying the registry for all records where `ownedBy` or `offeredBy` contains the organization's URI). 
  - **C1.** This would not solve point B2 above, however.

**Comment by cwd-mparsons** [comment]
@stuartasutton @siuc-nate @jkitchensSIUC 
This issue is probably better addressed in the vocabulary repository, as it is not specific to the registry assistant API.  I created a new issue in the latter repository:
https://github.com/CredentialEngine/vocabularies/issues/548

and closing this one
